services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    image: core:latest
    container_name: core_container
    tty: true                 # 対話的なプロンプトを維持
    stdin_open: true          # 標準入力を開いたままにする
    privileged: true # 多くのGUI/GPU設定で権限の問題を避けるために設定
    ipc: host # ホストのIPC名前空間を使用
    environment:
      - DISPLAY=${DISPLAY}             # ホストのディスプレイ番号をコンテナに渡す
      - QT_X11_NO_MITSHM=1           # Qtアプリケーションでのエラーを回避
      - XDG_RUNTIME_DIR=/tmp/runtime/  # Wayland互換性のための設定
      - ROS_DOMAIN_ID
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # X11ソケットの共有
      - ${HOME}/.Xauthority:/root/.Xauthority:ro # X認証情報（ホストでxhostを実行済みの場合）
      - .:/ros2_ws/src/
      - ros2_install_data:/ros2_ws/install # install フォルダを名前付きボリュームで永続化
      - ros2_build_data:/ros2_ws/build     # build フォルダを名前付きボリュームで永続化
      - /dev/ttyACM0:/dev/teensy # Teensyデバイスへのアクセスを許可
    working_dir: /ros2_ws
    command: bash -c "/ros2_ws/src/core_hardware/install_soem.sh && sleep infinity"
volumes:
  ros2_install_data:
  ros2_build_data:
