name: build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  release:
    types: [published]

jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        rosdistro:
          - humble

    runs-on: ${{ matrix.os }}

    container:
      image: ros:${{ matrix.rosdistro }}-ros-base

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup ROS2 workspace
        run: |
          mkdir -p /ros2_ws/src
          ln -s $GITHUB_WORKSPACE /ros2_ws/src/core2026

      - name: Install dependencies
        run: |
          apt-get update &&
          rosdep update &&
          rosdep install --from-paths /ros2_ws/src -i -y --rosdistro ${{ matrix.rosdistro }}

      - name: Install diagnostic-updater
        run: apt-get install -y ros-${{ matrix.rosdistro }}-diagnostic-updater

      - name: Build tests
        id: build_test
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
          cd /ros2_ws &&
          colcon build
        continue-on-error: true

      - name: build_test command success
        if: steps.build_test.outcome == 'success'
        run: echo "result - success"

      - name: build_test command failure
        if: steps.build_test.outcome == 'failure'
        run: echo "result - failure" && exit 1

      - name: Run tests
        id: run_test
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh &&
          cd /ros2_ws &&
          colcon test &&
          colcon test-result --verbose
        continue-on-error: true

      - name: run_test command success
        if: steps.run_test.outcome == 'success'
        run: echo "result - success"

      - name: run_test command failure
        if: steps.run_test.outcome == 'failure'
        run: echo "result - failure" && exit 1
